### ISSUE TITLE
1. 하이버 서비스 구조 파악 및 구조도 설계

### ISSUE THREAD

**Issue by namgonkim** [onepark-twokim/hiver_clone#3]
전체적인 하이버 서비스 구조를 파악하고 API에 따른 구조도를 설계합시다.

**Comment by namgonkim** [comment]
@kimkc @wonwon1 금일 중간 회의가 있습니다.
제가 그동한 작성한 구조 파악 ppt 링크 공유합니다.

https://docs.google.com/presentation/d/1OzPDLw68RkuM9lWTFG1UppK_y_hlJ42M4uM2ibe0SKE/edit?usp=sharing

**Comment by kimkc** [comment]
개념 구성도 및 API 리스트 초안
https://docs.google.com/presentation/d/10Zugb-VXzlybAIT9kDCGxPE4K3ugmZygicxVGIyPuRk/edit?usp=sharing

**Comment by namgonkim** [comment]
--------------------------------------------
6월 22일(화) 회의 진행 및 결과
--------------------------------------------
럭셔리 특가 - 특가까지 남은 시간 어떻게 처리하는지
쿠폰 발행 기능 - 어떻게 구현할지 쿠폰 적용처리 관련
결제 기능 - 가상 결제 기능으로 대체

남은 수량/ 남은 시간 : 실시간으로 페이지에 보여줘야 하는데 어떻게 처리할 것인가

어드민: 전체 쇼핌몰을 관리
슈퍼 어드민과, 셀럽 어드민 으로 나눠서 처리
슈퍼: 전체 쇼핑몰을 관리
셀럽: 자기네 쇼핑몰 관련 상품들만 관리
한 메뉴만 프로토타입으로 제작하면 나머지는 쉽게 할 수 있을 것 같다.

어드민과 쇼핑몰  상호 동작 처리/ 슈퍼 어드민과 셀럽 어드민 차이/ 쿠폰 발행과 적용가 처리/ 특가 상품 남은 시간 남은 수량 실시간 뷰어 처리

-----------------------------------------
향후 일정 계획
-----------------------------------------
6/26 토요일
1. API 리스트 작성하기
2. WBS 일정관리 작성하기

6/29 화요일
1. ERD 설계 중간 점검

7/3 토요일
1. ERD 설계 작성하기
2. API 정의서 중간 점검

7/6 화요일
1. API 정의서 작성하기
