### ISSUE TITLE
6월22일 리뷰

### ISSUE THREAD

**Issue by wonwon1** [onepark-twokim/hiver_clone#5]
럭셔리 특가 - 특가까지 남은 시간 어떻게 처리하는지
쿠폰 발행 기능 - 어떻게 구현할지 쿠폰 적용처리 관련
결제 - 

입점문의 / 어드민 페이지 

남은 수량/ 남은 시간 : 실시간으로 페이지에 보여줘야 하는데 어떻게 처리할 것인가

어드민: 전체 쇼핌몰을 관리
슈퍼 어드민과, 셀럽 어드민 으로 나눠서 처리
슈퍼: 전체 쇼핑몰을 관리
셀럽: 자기네 쇼핑몰 관련 상품들만 관리
한 메뉴만 프로토타입으로 제작하면 나머지는 쉽게 할 수 있을 것 같다.

어드민과 쇼핑몰  상호 동작 처리/ 슈퍼 어드민과 셀럽 어드민 차이/ 쿠폰 발행과 적용가 처리/ 특가 상품 남은 시간 남은 수량 실시간 뷰어 처리

6/26 토요일
1. API 리스트 작성하기
2. WBS 일정관리 작성하기

6/29 화요일
1. ERD 설계 중간 점검

토요일
1. ERD 설계 작성하기
2. API 정의서 중간 점검

화요일
1. API 정의서 작성하기

**Comment by namgonkim** [comment]
마일스톤 1주차 회의 issue로 이동합니다.
